1. Первое задание

In [8]:
import numpy as np

matrix = np.ones((3, 3))

vec = np.arange(3)

print(matrix + vec)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


2. Второе задание

In [9]:
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

axis_0 = np.sum((y > 3) & (y < 9), axis=0)
axis_1 = np.sum((y > 3) & (y < 9), axis=1)
axis_all = np.sum((y > 3) & (y < 9))

print(axis_0)
print(axis_1)
print(axis_all)

[1 1 1 1 1]
[2 3]
5
